services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: event-api-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - event-network
    depends_on:
      - db
      - cache

  web:
    image: nginx:alpine
    container_name: event-api-web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - event-network
    depends_on:
      - app

  db:
    image: postgres:17-alpine
    container_name: event-api-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: event_api
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - event-network

  cache:
    image: redis:7-alpine
    container_name: event-api-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - event-network

  queue:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: event-api-queue
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: php artisan queue:work
    networks:
      - event-network
    depends_on:
      - app
      - cache
      - db

  mailpit:
    image: axllent/mailpit:latest
    container_name: event-api-mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - event-network

networks:
  event-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
